import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ReduxProvider from '@/providers/ReduxProvider'
import NextUIProvider from '@/providers/NextUI'
import '@/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css'
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider signInFallbackRedirectUrl="/home/dashboard" dynamic>
        <html lang="en">
          <body className={inter.className}>
            <ReduxProvider>
              <NextUIProvider>
                {children}
              </NextUIProvider>
            </ReduxProvider>
          </body>
        </html>
    </ClerkProvider>
  )
}
