import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import ClientsProvider from '@/providers/ReduxProvider'
import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <ClientsProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ClientsProvider>
    </ClerkProvider>
  )
}
